language: python

python: "2.7"

install: "pip install -r requirements.txt --use-mirrors"

script: nosetests

language: python
python: 2.7
env:
- TOX_ENV=py27
- TOX_ENV=py34
- TOX_ENV=py35
install:
- pip install tox
script:
- tox -e $TOX_ENV

